TechDebt101
PublicDataWorks/complaint-manager pull request #393
Opened 2023-11-03 21:14 UTC by faraakhatTW

## Proposed changes

- Re-write MUI imports in `publicDataDashboard` 
- Fix failing test in clients and shared folder. 
Following TechDebt card [link]( https://github.com/PublicDataWorks/complaint-manager/issues/389)

## Types of changes

What types of changes does your code introduce to Complaint Manager?
_Put an `x` in the boxes that apply_

- [ ] Bugfix
- [ ] New feature
- [ ] Maintenance / Documentation Update

## Instance-files

- [ ] Do your changes require changes to instance-files?
  - if so please include a link to pull request for [instance-files demo](https://github.com/PublicDataWorks/instance_files_pm)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://publicdataworks.github.io/complaint-manager/technical-content/contributing.html) doc
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-11-03 21:36 UTC, heliofreitastw commented on src/client/publicDataDashboard/DashboardDataSection.js
> +import MUILink from "@material-ui/core/Link";
Should this import have the `Link as MUILink` like it was before? Looks like `MUILink` is a name someone gave to this import

2023-11-03 21:36 UTC, heliofreitastw commented on src/client/publicDataDashboard/DashboardAbout.js
> +import MUILink from "@material-ui/core/Link";
Same thing here with the `MUILink`.

2023-11-03 21:36 UTC, heliofreitastw commented on src/client/policeDataManager/shared/components/TextTruncate.test.js
> +configure({ adapter: new Adapter() });
what this code does?

2023-11-03 22:08 UTC, faraakhatTW commented on src/client/policeDataManager/shared/components/TextTruncate.test.js
> +configure({ adapter: new Adapter() });
this is telling Enzyme to use a specific adapter, corresponding for react version we are using. Basically it help setup Enzyme adapter globally in order to run test. Before that this test were throwing errors. Here is the link to a documentation [Link](https://enzymejs.github.io/enzyme/docs/installation/)

2023-11-03 22:14 UTC, faraakhatTW commented on src/client/publicDataDashboard/DashboardDataSection.js
> +import MUILink from "@material-ui/core/Link";
Its just naming convention which has no direct effect to a import itself as to Link as MUILink. MUILink serves same purpose. Its just shorter and better naming if we use different package that has export property like Link.

2023-11-06 15:53 UTC, heliofreitastw commented on src/client/policeDataManager/shared/components/TextTruncate.test.js
> +configure({ adapter: new Adapter() });
thank you

2023-11-06 15:54 UTC, heliofreitastw commented on src/client/publicDataDashboard/DashboardDataSection.js
> +import MUILink from "@material-ui/core/Link";
thank you

2023-11-06 15:54 UTC, heliofreitastw approved these changes

2023-11-06 16:40 UTC, sbhamani requested changes
Check the adapter comment

2023-11-06 16:40 UTC, sbhamani commented on src/client/publicDataDashboard/DashboardGlossary.test.js
> +configure({ adapter: new Adapter() });
If you look at /src/setupTests.js it already configures the Enzyme adapter and we shouldn't have to re-instantiate it here. See if these are able to run w/o re-instantiating and compare to other Enzyme tests that don't explicitly configure the adapter.

2023-11-06 19:32 UTC, sbhamani approved these changes

2023-11-06 20:05 UTC, merged